name: Continuous Integration
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - releases/**

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the app
        run: dotnet build

      - name: Test the app
        run: dotnet test

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./DotnetTemplate.Web/package-lock.json

      - name: Install dependencies
        working-directory: ./DotnetTemplate.Web
        run: npm ci

      - name: Build the TypeScript code
        working-directory: ./DotnetTemplate.Web
        run: npm run build

      - name: Lint the TypeScript code
        working-directory: ./DotnetTemplate.Web
        run: npm run lint

      - name: Test the TypeScript code
        working-directory: ./DotnetTemplate.Web
        run: npm t
